baseurl = "https://www.example.com/"
title = "コハク川雑録"
author = "David Hamp-Gonsalves"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

# google 分析
googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4


[taxonomies]
   tag = "tags"
   category = "categories"

[params]
  sitename = "コハク川雑録"
  disableWebFonts = false
  
  enableGiscus = true
  enableGitalk = false
  enableCommento = false

  comment = true

  
# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
clarity = "abcdefghzd"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[params.utterances]
    repo="your repo"
    term="[ENTER TERM HERE]"
    label="your label"
    theme="github-light"

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"

# 不可用 https://giscus.app/zh-CN
# [params.giscus]


[params.commento]
    commentoURL="https://cdn.commento.io"

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url  = "/blogs"
    weight = 2
[[menu.main]]
    name = "Tags"
    url  = "/tags"
    weight = 3
[[menu.main]]
    name = "Categories"
    url  = "/categories"
    weight = 4
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 0